version: '3.9'

services:
  app1:
    # build: ./app_1
    image: alvynabranches/app_1:latest
    restart: always
    networks:
    - apps

  app2:
    # build: ./app_2
    image: alvynabranches/app_2:latest
    restart: always
    networks:
    - apps

  app3:
    # build: ./app_3
    image: alvynabranches/app_3:latest
    restart: always
    networks:
    - apps
  
  app4:
    # build: ./app_4
    image: alvynabranches/app_4:latest
    restart: always
    networks:
    - apps

  app5:
    build: ./app_5
    image: alvynabranches/app_5:latest
    restart: always
    networks:
    - apps

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - app1
    - app2
    - app3
    - app4
    - app5
    ports:
    - 80:80
    networks:
    - apps

networks:
  apps: